"""add_membership_id

Revision ID: 4f1af1158aec
Revises: fbe32acc0767
Create Date: 2026-07-18 22:39:44.626410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f1af1158aec'
down_revision = 'fbe32acc0767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooperative_memberships', 'membership_status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='membershipstatus'),
               nullable=True,
               existing_server_default=sa.text("'active'::membershipstatus"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooperative_memberships', 'membership_status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='membershipstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::membershipstatus"))
    # ### end Alembic commands ###
