"""Add USSD onboarding codes

Revision ID: 6b09fb369e72
Revises: 4f1af1158aec
Create Date: 2026-07-18 23:40:29.817035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b09fb369e72'
down_revision = '4f1af1158aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooperative_memberships', sa.Column('farmer_code', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_cooperative_memberships_farmer_code'), 'cooperative_memberships', ['farmer_code'], unique=False)
    op.add_column('cooperatives', sa.Column('ussd_code', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_cooperatives_ussd_code'), 'cooperatives', ['ussd_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cooperatives_ussd_code'), table_name='cooperatives')
    op.drop_column('cooperatives', 'ussd_code')
    op.drop_index(op.f('ix_cooperative_memberships_farmer_code'), table_name='cooperative_memberships')
    op.drop_column('cooperative_memberships', 'farmer_code')
    # ### end Alembic commands ###
