"""add_subscription_tracking

Revision ID: fbe32acc0767
Revises: 010_unified_production
Create Date: 2026-07-18 22:26:23.385535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbe32acc0767'
down_revision = '010_unified_production'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('admin_action_confirmations_token_id_key', 'admin_action_confirmations', type_='unique')
    op.create_index(op.f('ix_admin_action_confirmations_id'), 'admin_action_confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_cooperative_attendances_membership_id'), 'cooperative_attendances', ['membership_id'], unique=False)
    op.drop_column('cooperative_attendances', 'farmer_id')
    op.execute("ALTER TABLE cooperative_memberships ALTER COLUMN membership_status DROP DEFAULT")
    op.execute("ALTER TABLE cooperative_memberships ALTER COLUMN membership_status TYPE membershipstatus USING membership_status::membershipstatus")
    op.execute("ALTER TABLE cooperative_memberships ALTER COLUMN membership_status SET DEFAULT 'active'::membershipstatus")
    op.alter_column('cooperative_memberships', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_cooperative_memberships_id'), 'cooperative_memberships', ['id'], unique=False)
    op.add_column('cooperatives', sa.Column('subscription_status', sa.String(), nullable=False, server_default='active'))
    op.add_column('cooperatives', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.drop_constraint('demo_bookings_reference_key', 'demo_bookings', type_='unique')
    op.create_index(op.f('ix_demo_bookings_id'), 'demo_bookings', ['id'], unique=False)
    op.drop_constraint('farmers_cooperative_id_fkey', 'farmers', type_='foreignkey')
    op.drop_column('farmers', 'crop_type')
    op.drop_column('farmers', 'cooperative_id')
    op.drop_column('farmers', 'membership_status')
    op.drop_column('farmers', 'acreage')
    op.drop_column('farmers', 'trust_score')
    op.create_index(op.f('ix_loans_membership_id'), 'loans', ['membership_id'], unique=False)
    op.drop_column('loans', 'farmer_id')
    op.create_index(op.f('ix_productions_membership_id'), 'productions', ['membership_id'], unique=False)
    op.drop_column('productions', 'farmer_id')
    op.add_column('transactions', sa.Column('settlement_line_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('disbursement_batch_id', sa.Integer(), nullable=True))
    op.drop_index('ix_transactions_pending_customer_action', table_name='transactions')
    op.create_index(op.f('ix_transactions_disbursement_batch_id'), 'transactions', ['disbursement_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_membership_id'), 'transactions', ['membership_id'], unique=False)
    op.create_index(op.f('ix_transactions_settlement_line_id'), 'transactions', ['settlement_line_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'disbursement_batches', ['disbursement_batch_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'settlement_lines', ['settlement_line_id'], ['id'])
    op.drop_column('transactions', 'farmer_id')
    op.create_index(op.f('ix_trust_scores_membership_id'), 'trust_scores', ['membership_id'], unique=False)
    op.drop_column('trust_scores', 'farmer_id')
    op.drop_column('ussd_sessions', 'farmer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ussd_sessions', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trust_scores', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trust_scores_membership_id'), table_name='trust_scores')
    op.add_column('transactions', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_settlement_line_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_membership_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_disbursement_batch_id'), table_name='transactions')
    op.create_index('ix_transactions_pending_customer_action', 'transactions', ['membership_id', 'status', 'customer_action'], unique=False)
    op.drop_column('transactions', 'disbursement_batch_id')
    op.drop_column('transactions', 'settlement_line_id')
    op.add_column('productions', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productions_membership_id'), table_name='productions')
    op.add_column('loans', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_loans_membership_id'), table_name='loans')
    op.add_column('farmers', sa.Column('trust_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('acreage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('membership_status', postgresql.ENUM('active', 'inactive', 'suspended', name='membershipstatus'), server_default=sa.text("'active'::membershipstatus"), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('cooperative_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('crop_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('farmers_cooperative_id_fkey', 'farmers', 'cooperatives', ['cooperative_id'], ['id'])
    op.drop_index(op.f('ix_demo_bookings_id'), table_name='demo_bookings')
    op.create_unique_constraint('demo_bookings_reference_key', 'demo_bookings', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_column('cooperatives', 'subscription_expires_at')
    op.drop_column('cooperatives', 'subscription_status')
    op.drop_index(op.f('ix_cooperative_memberships_id'), table_name='cooperative_memberships')
    op.alter_column('cooperative_memberships', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cooperative_memberships', 'membership_status',
               existing_type=sa.Enum('active', 'inactive', 'suspended', name='membershipstatus'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.add_column('cooperative_attendances', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cooperative_attendances_membership_id'), table_name='cooperative_attendances')
    op.drop_index(op.f('ix_admin_action_confirmations_id'), table_name='admin_action_confirmations')
    op.create_unique_constraint('admin_action_confirmations_token_id_key', 'admin_action_confirmations', ['token_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
